== SoFa Assignment - Pharox GHG Emissions Calculations

// image::./documentation/badges/coverage-branches.svg[Coverage branches]
image::./documentation/badges/coverage-functions.svg[Coverage functions]
image::./documentation/badges/coverage-lines.svg[Coverage lines]
image::./documentation/badges/coverage-statements.svg[Coverage statements]
image::./documentation/badges/coverage-jest%20coverage.svg[Jest coverage]

The assignment for this project is to build a modular application within Google Firebase that helps Pharox’s clients to:

    -	Calculate the GHG emissions of road-, rail-, air- and ocean transport in the supply chain upfront.
    -	Monitor the GHG-emissions of the execution.
    -	Provide management info where there is room to reduce the emissions.

The application should be integrated into the existing platforms like Smart Move, Smarti and Rail Easy or should feed our platforms.

The modular solution should be based on the GLEC Framework industry standard.

=== Repository Information

Some links to folders or files inside the repository are provided in order to facilitate the navigation through it

==== Analysis phase

    * link:./documentation/project-plan/ProjectPlan.pdf[Project plan]
    * link:./documentation/use-case-diagram/UseCaseDiagram.svg[Use case diagram]
    * link:./documentation/use-cases/UseCases.pdf[Use cases]
    * link:./documentation/test-case-scenarios/TestCaseScenarios.pdf[Test case scenarios]
    * link:./documentation/glec_considerations/emission_factor_retrieval.adoc[Considerations made for the GLEC framework]

==== Design phase

    * link:./documentation/activity-diagram[Activity diagrams]
      ** link:./documentation/activity-diagram/EmissionsCalculationActivityDiagram.svg[General Emissions Calculation Activity Diagram]
      ** link:./documentation/activity-diagram/EmissionsCalculationBasedOnPrimaryDataActivityDiagram.svg[Emissions Calculation Based On Primary Data Activity Diagram]
      ** link:./documentation/activity-diagram/EmissionsCalculationBasedOnDefaultDataActivityDiagram.svg[Emissions Calculation Based On Default Data Activity Diagram]
    * link:./documentation/sequence-diagram[Sequence diagrams]
    * link:./documentation/database-schema/DatabaseSchema.svg[Database schema]
    * link:./documentation/deployment-strategy/DeploymentStrategy.pdf[Deployment strategy]
    * link:./documentation/branching-strategy/BranchingStrategy.pdf[Branching strategy]
    * link:./documentation/conventions/Conventions.pdf[Code and naming conventions]

=== Implementation phase

    - link:./functions[Implementation]
    - link:https://fontysvenlo.github.io/sofa-project-pharox-ghg-emissions-calculation/[API documentation]

=== Useful links

    - link:https://niklas-mezynski-fontys.atlassian.net/jira/software/projects/SOFA/boards/1[Jira Project Board]

=== Firebase instructions
First time setup
[source,bash]
----
npm install -g firebase-tools
firebase login
----
To run firebase cloud functions locally, run the following command in the `functions/` directory of the project:

[source,bash]
----
npm run serve
----
This command will build the TypeScript project and start the firebase emulator. The emulator will be available at `http://127.0.0.1:4000/`.
The cloud functions will be available at `http://127.0.0.1:5001/pharox-sofa-project/us-central1/<function_name>`

=== Run OpenAPI view locally
First time setup
[source,bash]
----
npm install -g http-server
----

To run the OpenAPI view locally, run the following command in the `root` directory of the project:
[source,bash]
----
http-server --cors
----

The OpenAPI view will be available at `http://localhost:8080/`
