== SoFa Assignment - Pharox GHG Emissions Calculations
The assignment for this project is to build a modular application within Google Firebase that helps Pharox’s clients to:

    -	Calculate the GHG emissions of road-, rail-, air- and ocean transport in the supply chain upfront.
    -	Monitor the GHG-emissions of the execution.
    -	Provide management info where there is room to reduce the emissions.

The application should be integrated into the existing platforms like Smart Move, Smarti and Rail Easy or should feed our platforms.

The modular solution should be based on the GLEC Framework industry standard.

=== Repository Information

Some links to folders or files inside the repository are provided in order to facilitate the navigation through it

==== Analysis phase

    - link:./documentation/project-plan/ProjectPlan.pdf[Project plan]
//    - link:<./documentation/use-case-diagram/UseCaseDiagram.svg>[Use case diagram]
    - link:./documentation/use-case-scenarios/UseCaseScenarios.pdf[Use case scenarios]
    - link:./documentation/test-case-scenarios/UseCaseScenarios.pdf[Test case scenarios]

==== Design phase



=== Implementation phase



=== Useful links

    - link:https://niklas-mezynski-fontys.atlassian.net/jira/software/projects/SOFA/boards/1[Jira Project Board]
