openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://127.0.0.1:{port}/pharox-sofa-project/us-central1
    description: Local Development Server
    variables:
      port:
        default: "5001"
        description: Port where the local development server is running on
  # - url: https://us-central1-pharox-sofa-project.cloudfunctions.net
  #   description: Online Production Server
components:
  securitySchemes:
    authToken:
      type: http
      scheme: bearer
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
tags:
  - name: emission-calculations
    description: Functions related to operations regarding calculation of emissions
  - name: emission-factors
    description: Functions related to operations regarding emission factors
  - name: units
    description: Functions related to operations regarding units being used in the system
security:
  - bearerAuth: []
paths:
  /helloWorld:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /fetchClimatiq:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /addFuelEmissionFactor:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /addFuelEmissionFactors:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /getEmissionFactors:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /getEmissionFactorByActivity:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /emissionCalculator:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /scope1Calculation:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /unitClassification:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object
  /unitConverter:
    get:
      summary: Returns amount of emission factors saved in the DB
      description: Function that fetches the emission factors from Climatiq API and stores them in our DB
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A message saying the amount of emission factors saved
          content:
            application/json:
              schema:
                type: object