openapi: 3.0.3
info:
  title: GHG Emission Calculation API
  description: API to make the calculation of Greenhouse gasses emissions derived from a logistic activity. Built following the GLEC framework
  version: 0.0.0
servers:
  - url: http://127.0.0.1:{port}/pharox-sofa-project/us-central1
    description: Local Development Server
    variables:
      port:
        default: "5001"
        description: Port where the local development server is running on
  - url: https://us-central1-pharox-sofa-project.cloudfunctions.net
    description: Online Production Server
components:
  securitySchemes:
    authToken:
      type: http
      scheme: bearer
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    Fuel:
      $ref: "./swagger/schemas/emission_factors/fuel.yaml"
    Factor:
      $ref: "./swagger/schemas/emission_factors/factor.yaml"
    FuelFactor:
      $ref: "./swagger/schemas/emission_factors/fuel_factor.yaml"
    FuelEmissionFactor:
      $ref: "./swagger/schemas/emission_factors/fuel_emission_factor.yaml"
tags:
  - name: Emission calculations
    description: Functions related to calculation of emissions
  - name: Emission factors
    description: Functions related to emission factors
  - name: Units
    description: Functions related units being used in the system
security:
  - authToken: []
paths:
  /emissionCalculator:
    $ref: "./swagger/paths/emission_calculations/emission_calculator.yaml"
  /addFuelEmissionFactor:
    $ref: "./swagger/paths/emission_factors/add_fuel_emission_factor.yaml"
  /addFuelEmissionFactors:
    $ref: "./swagger/paths/emission_factors/add_fuel_emission_factors.yaml"
  /getFuelEmissionFactors:
    $ref: "./swagger/paths/emission_factors/get_fuel_emission_factors.yaml"
  /getFuelEmissionFactorById:
    $ref: "./swagger/paths/emission_factors/get_fuel_emission_factor_by_id.yaml"
  /getFuelEmissionFactorByFuelCode:
    $ref: "./swagger/paths/emission_factors/get_fuel_emission_factor_by_fuel_code.yaml"
  /getFuelEmissionFactorByRegion:
    $ref: "./swagger/paths/emission_factors/get_fuel_emission_factor_by_region.yaml"
  /getFuelEmissionFactorBySource:
    $ref: "./swagger/paths/emission_factors/get_fuel_emission_factor_by_source.yaml"
  /unitClassification:
    $ref: "./swagger/paths/units/unit_classification.yaml"
  /unitConverter:
    $ref: "./swagger/paths/units/unit_converter.yaml"