= Functions for calculation of GLEC framework's Scope 1 emissions 

== Introduction
This document will describe the necessary functions to perform the simple calculation of emissions for the Scope 1 of the GLEC framework.

== Retrieve emission factors 
This function will retrieve all the emission factors with the corresponding activity IDs from the Climatiq API website and stores it in firebase from where they can be later retrieved and used for performing emission calculations.

== Get emission factor by activity ID
This function takes the activity id as a parameter and returns the corresponding emission factor for this activity from the database.

== Perform emission calculation
This function will take the emission factor and the amount of fuel used to calculate the amount of emissions produced by using the specified amount of fuel. 

== Calculate Scope 1 emissions
This function combines the previously mentioned functions into one. It takes the amount of liters of fuel used and the activity ID. The activity ID is then passed to the function which retrieves the emission factor based on the activity ID which returns the corresponding emission factor. The amount of fuel and the emission factor are then passed to the emission calculation function which returns the corresponding emissions produced.
