= Delivery Meeting 03/11/2023

== Planning:

- Showcase Activity Diagram
- Showcase Emission Factors
  - Fuel Emission Factors
- Introduce Pharox to Swagger
  - Authentication
  - Live Demonstration
    - GLEC Framework Scope 1 Example
- Showcase Testing implementation
- Discuss Next Sprint
  - Start Scope 2 Emissions
    - Perform research to implement Scope 2
  - Refactoring Emission Factors from Database
  - Continue working on the reporting structure
  - Clean codebase
- Feedback and Questions for Pharox

== Notes (During Session):

- calculate per engine type and other factors depending (engine, etc) instead of fuel

often times you do not get an exact amount of fuel consumed but a combination of different information

** Send email on what order we are going to use**

Revamp project plan?

== What we agreed upon:

Pharox will send example data this afternoon

On Monday we will discuss the example data and determine a new roadmap

On Tuesday we meet with Pharox again to discuss our plan and if that aligns with what Pharox expects.

Ask Pharox to contact GLEC to get the data necessary

Send van den Ham a summary on what we discuss(ed) on Tuesday