
swagger: '2.0'
info:
  title: Emission Calculation API
  version: '1.0'
paths: {}
definitions:
  ValueWithUnit:
    type: object
    properties:
      value:
        type: number
      unit:
        type: string
  TransportDetail:
    type: object
    properties:
      consumedFuel:
        $ref: '#/definitions/ValueWithUnit'
      fuelCode:
        type: string
  TransportPart:
    type: object
    properties:
      distance:
        $ref: '#/definitions/ValueWithUnit'
      weight:
        $ref: '#/definitions/ValueWithUnit'
      transportDetails:
        $ref: '#/definitions/TransportDetail'
  FreightEmissionCalculationInput:
    type: object
    properties:
      metadata:
        type: object
        additionalProperties: true
      transportParts:
        type: array
        items:
          $ref: '#/definitions/TransportPart'
  ProducedEmissions:
    type: object
    properties:
      tankToWheel:
        type: number
      wellToTank:
        type: number
      wellToWheel:
        type: number
  EmissionIntensity:
    type: object
    properties:
      tkm:
        type: number
      value:
        type: number
      unit:
        type: string
  TransportActivity:
    type: object
    properties:
      producedEmissions:
        $ref: '#/definitions/ProducedEmissions'
      emissionIntensity:
        $ref: '#/definitions/EmissionIntensity'
      unit:
        type: string
      usedEmissionFactor:
        type: object
        additionalProperties: true
  CalculationReport:
    type: object
    properties:
      metadata:
        type: object
        additionalProperties: true
      transportActivities:
        type: array
        items:
          $ref: '#/definitions/TransportActivity'
      totalEmissions:
        type: number



swagger: '2.0'
info:
  title: Simple Emission Calculation API
  version: '1.0'
paths: {}
definitions:
  SimpleEmissionCalculationInput:
    type: object
    properties:
      usedFuel:
        type: number
        minimum: 0
      emissionFactor:
        type: number
        minimum: 0



swagger: '2.0'
info:
  title: Climatiq Emission Factors API
  version: '1.0'
paths: {}
definitions:
  ConstituentGases:
    type: object
    properties:
      co2eTotal:
        type: number
      co2eOther:
        type: number
      co2:
        type: number
      ch4:
        type: number
      n2o:
        type: number
  EmissionFactor:
    type: object
    properties:
      activityId:
        type: string
      id:
        type: string
      name:
        type: string
      category:
        type: string
      sector:
        type: string
      source:
        type: string
      sourceLink:
        type: string
      sourceDataset:
        type: string
      year:
        type: number
      yearReleased:
        type: number
      region:
        type: string
      regionName:
        type: string
      description:
        type: string
      unitType:
        type: string
      unit:
        type: string
      sourceLcaActivity:
        type: string
      dataQualityFlags:
        type: array
        items:
          type: string
      accessType:
        type: string
        enum:
          - public
          - private
      supportedCalculationMethods:
        type: array
        items:
          type: string
      factor:
        type: number
      factorCalculationMethod:
        type: string
      factorCalculationOrigin:
        type: string
      constituentGases:
        $ref: '#/definitions/ConstituentGases'
  ClimatiqEmissionFactor:
    allOf:
      - $ref: '#/definitions/EmissionFactor'
      - type: object
        properties:
          activity_id:
            type: string
          source_link:
            type: string
          source_dataset:
            type: string
          region_name:
            type: string
          unit_type:
            type: string
          source_lca_activity:
            type: string
          data_quality_flags:
            type: array
            items:
              type: string
          access_type:
            type: string
          supported_calculation_methods:
            type: array
            items:
              type: string
          factor_calculation_method:
            type: string
          factor_calculation_origin:
            type: string
          constituent_gases:
            $ref: '#/definitions/ConstituentGases'
  GetEmissionFactorQueryInput:
    type: object
    properties:
      activityId:
        type: string



swagger: '2.0'
info:
  title: Emission Factors API
  version: '1.0'
paths: {}
definitions:
  EmissionFactorInput:
    type: object
    properties:
      activityId:
        type: string
      activityType:
        type: string
      vehicleType:
        type: string
      fuelType:
        type: string
  CalculationDataInput:
    type: object
    properties:
      resourceAmount:
        type: number
        minimum: 0
      unit:
        type: string
  EmissionCalculatorInput:
    type: object
    properties:
      emissionDetails:
        $ref: '#/definitions/EmissionFactorInput'
      calculationDetails:
        $ref: '#/definitions/CalculationDataInput'
  Fuel:
    type: object
    properties:
      code:
        type: string
      description:
        type: string
  Factor:
    type: object
    properties:
      WTT:
        type: number
      TTW:
        type: number
      WTW:
        type: number
  FuelFactor:
    type: object
    properties:
      unit:
        type: string
        enum:
          - KG_CO2E_PER_KWH
          - KG_CO2E_PER_KG
          - KG_CO2E_PER_L
      factor:
        $ref: '#/definitions/Factor'
  FuelEmissionFactor:
    type: object
    properties:
      id:
        type: string
      source:
        type: string
        enum:
          - CUSTOM
          - GLEC
      fuel:
        $ref: '#/definitions/Fuel'
      factors:
        type: array
        items:
          $ref: '#/definitions/FuelFactor'
      region:
        type: string
        enum:
          - EU
          - NA
          - AF
          - AS
          - SA
          - OC
          - AN
          - INTERNATIONAL
  IntensityEmissionFactor:
    type: object
    properties:
      id:
        type: string
      source:
        type: string
        enum:
          - CUSTOM
          - GLEC
          - ISO
      freightType:
        type: string
        enum:
          - AIR
          - RAIL
          - ROAD
          - OCEAN
          - INLAND_WATERWAY
      vehicleType:
        type: string



swagger: '2.0'
info:
  title: Units API
  version: '1.0'
paths: {}
definitions:
  UnitType:
    type: string
    enum:
      - DISTANCE
      - WEIGHT
      - VOLUME
      - ELECTRICITY
      - UNKNOWN
  VolumeUnit:
    type: string
    enum:
      - ml
      - l
      - tsp
      - tbsp
  WeightUnit:
    type: string
    enum:
      - g
      - kg
      - tonnes
      - oz
      - lb
  DistanceUnit:
    type: string
    enum:
      - km
      - cm
      - m
      - in
      - ft
      - mi
  ElectricityUnit:
    type: string
    enum:
      - kWh



swagger: '2.0'
info:
  title: Common Models API
  version: '1.0'
paths: {}
definitions:
  ValueWithUnit:
    type: object
    properties:
      value:
        type: number
      unit:
        type: string


