== Introduction

This document is meant to provide a project plan that will define the guidelines for the realization of a GHG-Emissions application for the company Pharox.

The following project will be developed for Pharox in the context of the module SoFa, offered during the semester 7 at Fontys University of Applied Sciences in Venlo.

Pharox gives all users the power of smart data in real time. The apps and intelligent software make it immediately clear where your products, assets or container is and what condition it is in. A wide variety of organizations make use of Pharox every day to optimize their business process. Pharox represents a shift from reaction and hindsight to instant awareness and prediction.

“When it comes to product or process, you can now do much more than just hope for the best: you have the right to know that everything is working optimally regardless of the time, location, or supplier. Pharox's purpose is to provide process intelligence to professionals throughout the entire value chain, as they believe it's people that change the world, not things.” (Pharox, 2023)

Pharox is active in optimization of supply chains by digitisation with different technologies, like IoT, Planningstool, RPA and AI. Their IT landscape is based on full cloud serverless environment, cloud functions and they use amongst others Google Firebase, React, Stencil, Flutter, NodeJS for their solutions.
