name: build OpenAPI documentation

on:
  push:
    paths:
      - functions/**.ts
      - functions/**.js

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_openapi_docs:
    runs-on: ubuntu-latest
    name: Build OpenAPI documentation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install packages
        run: |
          cd functions
          npm ci

      - name: Build project
        run: |
          cd functions
          npm run build

      - name: Check for changes
        id: check_changes
        run: |
          git fetch
          git pull
          git add swagger-auto.yaml
          git diff --quiet || echo "::set-output name=changed::true"
        continue-on-error: true

      - name: Commit changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -a -m "Update OpenAPI documentation"
          git push
