name: Check for code coverage on PR

on:
    push:
    pull_request:
        types: [opened, edited]

# Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and test cloud functions
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3

            - name: Install packages
              run: |
                cd functions
                npm install

            - name: Jest coverage report                
              uses: ArtiomTr/jest-coverage-report-action@v2.2.5
              # give the id for the step, to access outputs in another step.
              id: coverage
              with:
                working-directory: functions
                test-script: npm test-build
                output: comment
