name: Pandoc

on:
  push:
    paths:
      - Documentation/ProjectPlan/**

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - uses: docker://pandoc/core:2.9
        with:
          args: "./Documentation/ProjectPlan/ProjectPlan.md > ProjectPlan.pdf" # gets appended to pandoc command
