name: build UseCaseScenarios asciidoc to pdf

on:
  push:
    paths:
      - documentation/use-cases/**

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  asciidoc_build:
    runs-on: ubuntu-latest
    name: Build Asciidoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build PDF
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf documentation/use-cases/UseCases.adoc -o documentation/use-cases/UseCases.pdf"

      - name: Commit PDF
        run: |
          git config --global user.email "j.sebastian@student.fontys.nl"
          git config --global user.name "Joel"
          git fetch
          git pull
          git add documentation/use-cases/UseCases.pdf
          git commit -a -m "Update Use Cases PDF"
          git push
